services:
  redis:
    image: 'bitnami/redis:latest'
    restart: unless-stopped
    ports:
      - '6379:6379'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - redis_data:/data

  # Note this container must be restarted to detect newly created queues
  # Repo: https://github.com/felixmosh/bull-board
  bullboard: # dashboard for the job queue
    container_name: cdd-bullboard
    image: deadly0/bull-board # Note: unofficial image
    restart: unless-stopped
    ports:
      - 3334:3000
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    environment:
      REDIS_HOST: host.docker.internal

  alice:
      image: ${CHAIN_IMAGE}
      init: true # Faster shutdown by container process not be PID 1
      restart: unless-stopped
      ports: # expose ports to localhost
        - '9944:9944' # ws://
        - '9933:9933' # http://
        - '30333:30333' # for other nodes
      extra_hosts:
        - 'host.docker.internal:host-gateway'
      volumes:
        - './chain-entry.sh:/chain-entry.sh'
      entrypoint: '/chain-entry.sh'
      command:
        [
          '--alice --chain dev',
        ]

volumes:
  redis_data: